update: runner for build

diff --git a/.github/workflows/release-mobile-app.yaml b/.github/workflows/release-mobile-app.yaml
--- a/.github/workflows/release-mobile-app.yaml
+++ b/.github/workflows/release-mobile-app.yaml
@@ -1,8 +1,8 @@
-name: Mobile fastlane release workflow
+name: Deploy to Firebase
 on:
   push:
     tags:
-      - mobile/v*.*.*
+      - mobile/v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
   workflow_dispatch:
 
 jobs:
@@ -107,75 +107,71 @@ jobs:
   # FILE_PATH: "/OWalletKeystore"
   release-ios-mobile:
     name: release-ios-mobile
-    runs-on: macos-13 #orai-self-hosted
+    runs-on: macos-latest-xlarge #orai-self-hosted
     timeout-minutes: 120 # Set the timeout to 120 minutes
     strategy:
       matrix:
         node-version: [20.17.0]
     steps:
-      - name: Check tag name
-        if: contains(github.ref, 'cp')
-        run: |
-          exit 1
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.8.0
         with:
           access_token: ${{ github.token }}
+#      - name: Install xcodes
+#        run: brew install xcodes
+      #  - name: Install Xcode 15.4
+      #    run: xcodes install 15.4 --experimental-unxip || true
+#      - name: Select Xcode 15.2
+#        run: xcodes select 15.2
+      - name: Verify Xcode version
+        run: xcodebuild -version
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Increase Node.js memory limit to 7GB
-        run: |
-          export NODE_OPTIONS="--max-old-space-size=7168"
-      - name: Get yarn cache directory path
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-      - name: Restore node_modules from cache
-        uses: actions/cache@v2
-        id: yarn-cache
+      - name: Checkout Repository with Submodules
+        uses: actions/checkout@v4
         with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          submodules: true
+          fetch-depth: 0
+          ssh-key: ${{ secrets.SSH_DEPLOY_KEY_MAIN }}
+      - name: Get Yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
+      - name: Cache Yarn dependencies
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ steps.yarn-cache-dir-path.outputs.dir }}
+            .yarn/cache
+            .yarn/install-state.gz
+            !.eslintcache # Exclude eslint cache
+          key: ${{ runner.os }}-yarn-${{ github.sha }}  # Cache per commit
           restore-keys: |
             ${{ runner.os }}-yarn-
-      - name: Checkout submodule repo
-        uses: actions/checkout@v3
-      - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
-        run: yarn install --frozen-lockfile
-      - name: Install mobile packages
-        working-directory: apps/mobile
-        run: yarn --silent
-      - name: Build mobile images
-        working-directory: apps/mobile
-        run: yarn images
-      - name: restore lerna
-        uses: actions/cache@v3
-        with:
-          path: "**/node_modules"
-          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
+      - name: Install dependencies
+        run: |
+          yarn install
       - name: Build Libs
-        run: yarn build:codepush
-
-      - name: Build @owallet/hooks
-        working-directory: packages/hooks
-        run: yarn build:hooks
-
-      - name: Build @owallet/hooks-internal
-        working-directory: apps/hooks-internal
-        run: yarn build:hooks-internal
-
-      - name: Bundle mobile
+        run: yarn build:libs
+      #      - name: Setup environment variables
+      #        working-directory: apps/mobile
+      #        run: |
+      #          echo "SENTRY_TOKEN=${{ secrets.SENTRY_TOKEN }}" >> .env
+      #          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
+      #          echo "SENDER_ID=${{ secrets.SENDER_ID }}" >> .env
+      #          echo "APP_ID=${{ secrets.APP_ID }}" >> .env
+      #          echo "MIX_PANEL_TOKEN=${{ secrets.MIX_PANEL_TOKEN }}" >> .env
+      #          echo "BYTE_BREW_SDK_KEY_IOS=${{ secrets.BYTE_BREW_SDK_KEY_IOS }}" >> .env
+      #          echo "BYTE_BREW_ID_IOS=${{ secrets.BYTE_BREW_ID_IOS }}" >> .env
+      - name: Setup environment variables
         working-directory: apps/mobile
-        run: yarn build:ios
+        run: yarn bundle:ios
         env:
           SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
-          API_KEY_ETH_SCAN: ${{ secrets.API_KEY_ETH_SCAN }}
-          API_KEY_BSC_SCAN: ${{ secrets.API_KEY_BSC_SCAN }}
           API_KEY: ${{ secrets.API_KEY_FIREBASE }}
           SENDER_ID: ${{ secrets.SENDER_ID_FIREBASE }}
           APP_ID: ${{ secrets.APP_ID_FIREBASE }}
-          API_KEY_KADO: ${{ secrets.API_KEY_KADO }}
           MIX_PANEL_TOKEN: ${{ secrets.MIX_PANEL_TOKEN }}
           BYTE_BREW_SDK_KEY_IOS: ${{ secrets.BYTE_BREW_SDK_KEY_IOS }}
           BYTE_BREW_ID_IOS: ${{ secrets.BYTE_BREW_ID_IOS }}
@@ -184,12 +180,23 @@ jobs:
         with:
           ruby-version: 3.2
           bundler-cache: true
+      - name: Cache Pods
+        uses: actions/cache@v3
+        id: pods-cache
+        with:
+          path: ./apps/mobile/ios/Pods
+          key: ${{ runner.os }}-pods-${{ hashFiles('apps/mobile/ios/Podfile.lock') }}
       - name: Pod install
         working-directory: apps/mobile
         run: yarn pod:install
-      - name: Setup Fastlane ios
+      - name: Decode and Set GOOGLE_APPLICATION_CREDENTIALS
         working-directory: apps/mobile/ios/fastlane
-        run: cd .. && bundle update && fastlane release
+        run: |
+          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}" | base64 -d > $GITHUB_WORKSPACE/owallet-829a1-3cfff653dc5e.json
+          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/owallet-829a1-3cfff653dc5e.json" >> $GITHUB_ENV
+      - name: Setup Fastlane ios
+        working-directory: apps/mobile/ios
+        run: bundle update
         env:
           DISCORD_HOOK_ID: ${{ secrets.DISCORD_MOBILE_WEBHOOK_ID }}
           DISCORD_HOOK_TOKEN: ${{ secrets.DISCORD_MOBILE_WEBHOOK_TOKEN }}
@@ -209,3 +216,8 @@ jobs:
           MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
           SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
           MIX_PANEL_TOKEN: ${{ secrets.MIX_PANEL_TOKEN }}
+          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
+
+      - name: Cleanup Google Credentials
+        if: always()  # Run even on failure
+        run: rm -f $GITHUB_WORKSPACE/owallet-829a1-3cfff653dc5e.json
